services:
  mariadb:
    build:
      context: ./requirements/mariadb  
    restart: always
    volumes:
      - mariadb:/var/lib/mysql  
    networks:
      - wordpress-network
    ports: 
      - "3306"
    env_file: .env
  
  wordpress:
    build:
      context: ./requirements/wordpress 
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html  
    networks:
      - wordpress-network
    ports: 
      - "9000"
    env_file: .env

  nginx:
    build:
      context: ./requirements/nginx  
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443" 
    networks:
      - wordpress-network
    volumes: 
      - wordpress:/var/www/html
    env_file: .env

networks:
  wordpress-network:
    driver: bridge
volumes: 
  wordpress:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/vphilipp/data/wordpress
  mariadb:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/vphilipp/data/mariadb
