services:
  mariadb:
    build:
      context: ./requirements/mariadb  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /home/vphilipp/data/mariadb:/var/lib/mysql  
    networks:
      - wordpress-network
    ports: 
      - "3306"
    # No healthcheck for now
  
  wordpress:
    build:
      context: ./requirements/wordpress 
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - /home/vphilipp/data/wordpress:/var/www/html  
    networks:
      - wordpress-network
    ports: 
      - "9000"
  nginx:
    build:
      context: ./requirements/nginx  
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443" 
    volumes:
      - /home/vphilipp/data/wordpress:/var/www/html 
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge
